spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  profiles:
    active: prod
light-security:
  jwt:
    algorithm: hs512
    secret: http-security-secret-modify-mehttp-security-secret-modify
    expiration-in-second: 1209600

keyword:
  percent: 0.1
